# Generated by Django 2.0.1 on 2018-02-26 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificacionEvento',
            fields=[
                ('idClasificacion_evento', models.AutoField(primary_key=True, serialize=False)),
                ('Clasificacion_evento', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_cliente', models.TextField()),
                ('Apellido_cliente', models.TextField()),
                ('Telefono_cliente', models.TextField()),
                ('Correo_electronico', models.TextField()),
                ('Otros_datos_cliente', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DetalleEvento',
            fields=[
                ('idDetalle_evento', models.AutoField(primary_key=True, serialize=False)),
                ('FechaInicio', models.DateField()),
                ('FechaFin', models.DateField()),
                ('ClasificacionEvento_idClasificacionEvento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agenda.ClasificacionEvento')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('idEvento', models.AutoField(primary_key=True, serialize=False)),
                ('NombreEvento', models.TextField()),
                ('CodigoEvento', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EventoCliente',
            fields=[
                ('idEventoCliente', models.AutoField(primary_key=True, serialize=False)),
                ('ClienteIdCliente', models.IntegerField()),
                ('EventoIdEvento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agenda.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='EventoMaterial',
            fields=[
                ('idEventoMaterial', models.AutoField(primary_key=True, serialize=False)),
                ('EventoIdEvento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('idMaterial', models.AutoField(primary_key=True, serialize=False)),
                ('CodigoMaterial', models.TextField()),
                ('nombreMaterial', models.TextField()),
                ('CantidadIdeal', models.IntegerField()),
                ('CantidadInicial', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='eventomaterial',
            name='MaterialIdMaterial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agenda.Material'),
        ),
        migrations.AddField(
            model_name='detalleevento',
            name='Evento_idEvento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agenda.Evento'),
        ),
    ]
