# Generated by Django 2.0.1 on 2018-02-26 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0002_auto_20180226_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventocliente',
            name='ClienteIdCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agenda.Cliente'),
        ),
    ]
