# Generated by Django 2.0.1 on 2018-02-26 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0003_auto_20180226_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventomaterial',
            name='EventoIdEvento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agenda.Evento'),
        ),
    ]
