# Generated by Django 2.0.1 on 2018-02-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0004_auto_20180226_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasificacionevento',
            name='Clasificacion_evento',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Apellido_cliente',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Correo_electronico',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Nombre_cliente',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Telefono_cliente',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='evento',
            name='CodigoEvento',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='evento',
            name='NombreEvento',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='material',
            name='CodigoMaterial',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='material',
            name='nombreMaterial',
            field=models.CharField(max_length=45),
        ),
    ]
